services:
  frontend:
    image: todo-front-prod
    container_name: todo-front-prod
    build:
      context: ./todo-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy-prod
    depends_on:
      - frontend
  mongo:
    image: mongo
    container_name: todo-mongo-prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
        - todos_mongo:/data/db
        - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis
    container_name: todo-redis-prod
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - todos_redis:/data
  backend:
    image: todo-backend-prod
    container_name: todo-backend-prod
    build:
      context: ./todo-backend
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

volumes:
  todos_mongo:
  todos_redis:
